INSERT INTO tb_processos (nome, nro_processo, img_url, descricao_curta, descricao_longa) VALUES ('proj1', '1',  'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/1.png', 'Descricao curta para o projeto nomero 1', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_processos (nome, nro_processo, img_url, descricao_curta, descricao_longa) VALUES ('proj2', '2',  'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/2.png', 'Descricao curta para o projeto nomero 2', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_processos (nome, nro_processo, img_url, descricao_curta, descricao_longa) VALUES ('proj3', '3',  'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/3.png', 'Descricao curta para o projeto nomero 3', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_processos (nome, nro_processo, img_url, descricao_curta, descricao_longa) VALUES ('proj4', '4',  'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/4.png', 'Descricao curta para o projeto nomero 4', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_processos (nome, nro_processo, img_url, descricao_curta, descricao_longa) VALUES ('proj5', '5',  'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/5.png', 'Descricao curta para o projeto nomero 5', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_processos (nome, nro_processo, img_url, descricao_curta, descricao_longa) VALUES ('proj6', '6',  'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/6.png', 'Descricao curta para o projeto nomero 6', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_processos (nome, nro_processo, img_url, descricao_curta, descricao_longa) VALUES ('proj7', '7',  'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/7.png', 'Descricao curta para o projeto nomero 7', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_processos (nome, nro_processo, img_url, descricao_curta, descricao_longa) VALUES ('proj8', '8',  'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/8.png', 'Descricao curta para o projeto nomero 8', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_processos (nome, nro_processo, img_url, descricao_curta, descricao_longa) VALUES ('proj9', '9',  'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/9.png', 'Descricao curta para o projeto nomero 9', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_processos (nome, nro_processo, img_url, descricao_curta, descricao_longa) VALUES ('proj10','10', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/10.png', 'Descricao curta para o projeto nomero 10', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');

INSERT INTO tb_pessoas (nome, CPF_CNPJ, telefone, email) VALUES ('Joao Gonçalves','22222222222', '04999999999', 'joao@gmail.com');
INSERT INTO tb_pessoas (nome, CPF_CNPJ, telefone, email) VALUES ('Maria wilms','33333333333',    '04812333453', 'maria@gmail.com');
INSERT INTO tb_pessoas (nome, CPF_CNPJ, telefone, email) VALUES ('Pedro hoss','22222889977', '04199999991', 'pedro@gmail.com');
INSERT INTO tb_pessoas (nome, CPF_CNPJ, telefone, email) VALUES ('Jilia bigorna','22222299998', '04599999992', 'julia@gmail.com');

INSERT INTO tb_docs(descricao, url) values('abertura do processo','http://gdoc.com.br/arq01');
INSERT INTO tb_docs(descricao, url) values('atualizacao do processo','http://gdoc.com.br/arq02');
INSERT INTO tb_docs(descricao, url) values('juri do processo','http://gdoc.com.br/arq03');
INSERT INTO tb_docs(descricao, url) values('recurso do processo','http://gdoc.com.br/arq04');
INSERT INTO tb_docs(descricao, url) values('abesc do processo','http://gdoc.com.br/arq05');
